### ISSUE TITLE
Sync-sources deployment SUBTASK not detecting changes in inherited files

### ISSUE THREAD

**Issue by leomassazza** [Synthetixio/synthetix-v3#199]
How to reproduce:
1- do a clear deploy
2- update a module's inherited file. i.e. add a new variable to GlobalNamespace.GlobalStorage (append)
3- do a new deploy (without --clear)
Check the deployer output.

```

Compiling 3 files with 0.8.4
Compilation finished successfully


┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ‣ Syncing solidity sources with deployment data....................................... ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
✓ Deployment data is in sync with sources
```
as you can see, it compiled 3 files (one namespace and two modules that inherited it) but Sync solidity sources says that the deployment data is in sync.

**Comment by mjlescano** [comment]
This was already fixed, when we implemented updates checking by using `deployedBytecode` here: https://github.com/Synthetixio/synthetix-v3/blob/ee244c9f059279b6c889dc38423c00b688ce33c0/packages/deployer/internal/contract-helper.js#L7:L19
