### ISSUE TITLE
Enforce no invisible whitespaces in linters

### ISSUE THREAD

**Issue by ajsantander** [Synthetixio/synthetix-v3#208]
<img width="409" alt="Screen Shot 2021-10-04 at 12 19 11" src="https://user-images.githubusercontent.com/550409/135878129-ab6fbdac-e475-4a8f-a331-6c35fc3cf28a.png">

**Comment by mjlescano** [comment]
Solhint currently doesn't have a rule for validating trailing whitespace: https://protofire.github.io/solhint/
But, we're checking it with Prettier, so, if you run `npm run lint` it will still throw an error. It's not the best output for the user, but it is being checked, I think we could leave it like it is right now. What do you think @ajsantander?

**Comment by ajsantander** [comment]
> Solhint currently doesn't have a rule for validating trailing whitespace: https://protofire.github.io/solhint/ But, we're checking it with Prettier, so, if you run `npm run lint` it will still throw an error. It's not the best output for the user, but it is being checked locally and on CI, I think we could leave it like it is right now. What do you think @ajsantander?

Ok, so if lint:fix removes the whitespace we should be ok.
If so, pls close this issue.
