### ISSUE TITLE
core-modules tests fail if ran twice locally

### ISSUE THREAD

**Issue by leomassazza** [Synthetixio/synthetix-v3#407]
In Core-modules tests I had to add the bootstrap to all the tests (even unit tests) since otherwise the system will fail with` Error: Router is not valid.`

The origin of the Router is not valid error is that the generated router points to a previous version of the instances. i.e. errors like 
`☠ Selector 0x1627540c not reachable. _CORE_OWNER_MODULE pointing to 0x0165878A594ca255338adfa4d48449f69242Eb8F instead of 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512 `
are shown for all selectors

----  
Here a sample of the additions to the tests:

```
...
const bootstrap = require('../../helpers/bootstrap'); // ADDED

const { ethers } = hre;

describe('CoreOwnerModule', () => {
  bootstrap(); // ADDED
...
```

**Comment by ajsantander** [comment]
Deprecated by work being done in #456
