### ISSUE TITLE
Coverage is always failing, even in PRs that increase coverage (see closed PRs)

### ISSUE THREAD

**Issue by ajsantander** [Synthetixio/synthetix-v3#518]

**Comment by leomassazza** [comment]
As far as I can see, the coverage failing is due to:
1- new paths open that aren't covered in the same repo (i.e. deployer adding options to log or not)
2- code size changes. `lines_covered/total_lines` can be reduced by either reducing lines_covered or increasing total_lines.

**Comment by mjlescano** [comment]
Looks like it was caused because the going to be merged PR wasn't updated with the last changes from `main`. Will close the issue for now and re-open if it happens again.
