### ISSUE TITLE
Design dismissal functionality in the ElectionModule

### ISSUE THREAD

**Issue by mjlescano** [Synthetixio/synthetix-v3#533]
How will the ElectionModule handle the dismissal of members of the council, or the entire council?

**Comment by ajsantander** [comment]
When the ElectionModule is first initialized, it only has a single council member, the owner of the system that hosts the ElectionModule. As such, the first epoch is "fast forwarded" immediately to the nomination phase for the second epoch. Such fast forward mechanism is considered an emergency election state.

Community members may call `dismiss(address[] members)` to use their voting power to attempt to dismiss one or more council members. Voting power is counted with a dismissal strategy (similar to the election strategy) and for every member that meets the `dismissalThresholdPercent` (which is a percent of the total supply), the member is automatically dismissed and its NFT burnt.

If dismissals produce a number of active council members beneath `minimumActiveSeats`, the ElectionModule enters an emergency election state, which is identical to the state that the module is in in its first epoch. I.e. the epoch is fast forwarded to the nomination phase for the next epoch.

If all council members are dismissed during such an event, then the owner is re-assigned as the only council member.
