### ISSUE TITLE
Bug: router not updated after fixing a selector collision

### ISSUE THREAD

**Issue by leomassazza** [Synthetixio/synthetix-v3#59]
Steps to reproduce:
- have a basic system working
- deploy it: npx hardhat deploy --network local --clear
- create a new module/contract with a function similar to other contract (same name and parameters)
- deploy it: npx hardhat deploy --network local --clear
    - you're going to see an error found by the tooling indicating there's a selector collision
- rename the function on the new contract created
- try to deploy it again: npx hardhat deploy --network local --clear
    - the error is not detected by the tooling (in fact the router is not updated) but by the solidity compiler. In order to continue working the dev should delete manually the router.

**Comment by ajsantander** [comment]
Yep, the router code generator should blow up as soon as it sees two identical selectors
