### ISSUE TITLE
Ask product about spreading votes (different vote power for different candidates)

### ISSUE THREAD

**Issue by ajsantander** [Synthetixio/synthetix-v3#656]

**Comment by leomassazza** [comment]
question about the different approaches of Voting methods that are available and what do we want to implement from prod. perspective when moving to more than one candidate per ballot.

The main options I see are:

A- Preference: not-ordered list of support-for candidate
B- Ranked:  ordered list of candidates, where all voting power count to one of them i.e. STV
C- Cumulative:  each voter is assigned a number of points to distribute on the list. i.e. 10 points given, I choose 5 to the first, 3 to the 2nd, 2 to the 3rd in the list.
D- Score: points or percentage or "value" for each position in the ordered list. Similar to cumulative, but the points are already set.
E- Vote Power distribution: the voter set how to distribute his vote-power. i.e. 40% for the first, 30% to the second,  20% to the 4th and 10% for the 5th.
F-  For/Against: voters can choose to give 1 point or -1 point to single or multiple candidates. 

All has their theoretical pros and cons but I prefer the pragmatic/behavioral best options for us here. I think A, B, and E are the more natural and useful for us, but I prefer to have the product vision here.

**Kain | Synthetix — Yesterday at 10:54 PM**

My view is B mainly for consistency with V2x, I think that we should eventually allow V3GM to support all of these options or any other novel voting strategy, but for not our scope should be replacing v2x
