### ISSUE TITLE
Why does core-modules have contracts/mocks/modules/ and contracts/modules/mocks/ ?

### ISSUE THREAD

**Issue by mjlescano** [Synthetixio/synthetix-v3#664]

**Comment by mjlescano** [comment]
Because we want the ones inside `modules` to be usable behind the Router, and have access to the shared Storage.

**Comment by mjlescano** [comment]
Right now, we only have `mocks/modules/WrongModuleMock.sol` on `mocks/modules`, we could maybe move it to `mocks/WrongModuleMock.sol` to avoid confusions.

**Comment by ajsantander** [comment]
Fixed directly in main (just moved the file)
