### ISSUE TITLE
Clean up list

### ISSUE THREAD

**Issue by ajsantander** [Synthetixio/synthetix-v3#67]
- [x] Stop using hre.deployer.paths
- [ ] Do not use config in any tools - tools should only use primitives that are very intuitive
- [ ] Do not copy config.paths into config.deployer.paths
- [ ] Do not use config.deployer for anything dynamic, since this is supposed to be just config
- [ ] Forbid usage of `.previousData` in hre.deployer?
- [ ] Forbid usage of `.file` in hre.deployer?
- [ ] Is config.deployer.proxyName used?
- [ ] Document argument-types.js util
- [ ] Split out some functions in contracts util to core-js
- [x] Move logger to core-js
- [x] Move git and package to core-js
- [x] Move prompter to core-js
- [x] Move relative-path to core-js
- [x] Move string to core-js
- [ ] Split deployer utils to internal/external utils: Internal are those that need the hre env, and external are the ones that dont - E.g. transactions.js

**Comment by leomassazza** [comment]
for  `Is config.deployer.proxyName used?` 
I can answer: Yes.
And in fact I think we should also add the "Gen" prefix as configurable and defaulted to "Gen" so that the tooling doesn't enforce you to use a particular name for the generated contracts (or any hardcoded name).

**Comment by ajsantander** [comment]
Closing this issue. Splitting it up in smaller issues.
