### ISSUE TITLE
InitializableModules: Check security impact of _isInitialized() with complex logic

### ISSUE THREAD

**Issue by leomassazza** [Synthetixio/synthetix-v3#717]

**Comment by ajsantander** [comment]
Yeah, good points all around.

After these considerations, wouldn't you feel better with the original idea of using a dedicated boolean? `store.isInitialized = true`.

**Comment by leomassazza** [comment]
> 

I prefer that option, and I might change the examples to use it so that the pattern is installed, but I don't like the idea of enforcing it.

**Comment by leomassazza** [comment]
Created Issue # 749
